steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/cgs-agent-shell/shell:$COMMIT_SHA
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/cgs-agent-shell/shell:latest
      - -f
      - deploy/Dockerfile
      - .
  - name: "gcr.io/cloud-builders/docker"
    args:
      - push
      - --all-tags
      - us-central1-docker.pkg.dev/$PROJECT_ID/cgs-agent-shell/shell
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - run
      - deploy
      - cgs-agent-shell
      - --image=us-central1-docker.pkg.dev/$PROJECT_ID/cgs-agent-shell/shell:$COMMIT_SHA
      - --region=us-central1
      - --platform=managed
images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/cgs-agent-shell/shell:$COMMIT_SHA
  - us-central1-docker.pkg.dev/$PROJECT_ID/cgs-agent-shell/shell:latest
options:
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
